### PR TITLE
Set pointer-events-auto class on HomepageHero text

### PR DESCRIPTION
**Pull request by AdamAnSubtractM**
Set pointer-events to none for the HomepageHero canvas so that text can be selected.

### CODE REVIEW

**Comment by lucacasonato** [comment]
Not allowing to select the hero text was intentional: https://github.com/jsr-io/jsr/pull/115. Is there a specific issue you are running into?

**Comment by AdamAnSubtractM** [comment]
> Not allowing to select the hero text was intentional: #115. Is there a specific issue you are running into?

Did not realize this was intentional. I was trying to copy and paste the text to send to someone and noticed I could not. Seemed like a usability issue to me and opened a PR. If the JSR team feels users shouldn't be able to select text on the page, then I don't think Its my place to say otherwise. 

Let me know if you want me to close this, otherwise, feel free to decline. Thanks for your time.

**Comment by josh-collinsworth** [comment]
@AdamAnSubtractM Thanks for the contribution! I agree; this is an issue for usability.

However, this approach prevents some interactions with the background. I believe the better way to achieve the desired outcome would be to simply add the `pointer-events-auto` class to the `<div>` that contains the text in question. That will allow its text to be selectable, while keeping everything around it as-is.

**Comment by AdamAnSubtractM** [comment]
> @AdamAnSubtractM Thanks for the contribution! I agree; this is an issue for usability.
> 
> However, this approach prevents some interactions with the background. I believe the better way to achieve the desired outcome would be to simply add the `pointer-events-auto` class to the `<div>` that contains the text in question. That will allow its text to be selectable, while keeping everything around it as-is.

Thanks @josh-collinsworth . I'll update the PR with your suggestions.

**Comment by AdamAnSubtractM** [comment]
> @AdamAnSubtractM Thanks for the contribution! I agree; this is an issue for usability.
> 
> However, this approach prevents some interactions with the background. I believe the better way to achieve the desired outcome would be to simply add the `pointer-events-auto` class to the `<div>` that contains the text in question. That will allow its text to be selectable, while keeping everything around it as-is.

@josh-collinsworth  - PR updated, thanks.

**Review by josh-collinsworth — APPROVED** [review]
Perfect, thanks!

**Pull request merged**
