### PR TITLE
Fix website horizontal scroll

### PR DESCRIPTION
**Pull request by MattheousDT**
Website has a horizontal scrollbar on operating systems (Windows etc.) that have permanent scrollbars.

### CODE REVIEW

**Comment by lucacasonato** [comment]
@MattheousDT Where are you seeing this? Can you post a screenshot?

**Comment by MattheousDT** [comment]
Firefox
image

Chromium
image

Note the horizontal scrollbar at the bottom. Happens regardless of window size

**Comment by lucacasonato** [comment]
Thanks. This seems to be happening because of the `width: 100vw` on the canvas for particle.js.

@josh-collinsworth PTAL

**Comment by josh-collinsworth** [comment]
> Thanks. This seems to be happening because of the `width: 100vw` on the canvas for particle.js.
> 
> @josh-collinsworth PTAL

Will do. This looks good at a glance but I want to take some time to thoroughly test to make sure there aren't other side effects.

**Comment by josh-collinsworth** [comment]
I have what I think is a more preferable implementation here: https://github.com/jsr-io/jsr/pull/134

It's the same fix/CSS, but just applied _only_ to the homepage, just so we avoid any unforeseen side effects, or situations where we might _want_ horizontal overflow.

Thanks for reporting and opening this!

**Pull request closed without merging**
